stages:
  - deploy

deploy-develop:
  stage: deploy
  image: alpine:latest
  environment:
    name: develop
    url: https://nxtch.devmy.it/
  before_script:
    - apk update
    - apk add openssh
    - if [ -z "$SSH_PRIVATE_KEY" ] || [ -z "$VM_IPADDRESS" ] || [ -z "$SSH_PORT" ] || [ -z "$SSH_USER" ]; then exit 1;  fi
    - mkdir -p ~/.ssh && echo "${SSH_PRIVATE_KEY}" >> ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
  script:
    - ssh -o ConnectTimeout=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -n -q -T -l $SSH_USER -p $SSH_PORT $VM_IPADDRESS "~/update_magentoCommerce.sh"
  allow_failure: true
  only:
    - develop
